
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jspid
    url: jdbc:mysql://localhost3306/jsptest
    #url: jdbc:mysql://localhost:3306/jsptest?characterEncoding=UTF-8&serverTimezone=UTC
    password: jsppass
  application:
    name: connectmysql
  thymeleaf:
    cache: 'false'
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# Mapper Xml Location
mybatis:
  mapper-locations: 
    classpath:mapper/**/*.xml


